name: so_link
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cloud_firestore: ^6.1.2
  dotenv: ^4.2.0
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  gap: ^3.0.1
  google_fonts: ^8.0.2
  provider: ^6.1.5+1
  skeletonizer: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
